name: Build & Release VS Code Extension

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: npm

      - name: Setup vsce
        run: npm install -g @vscode/vsce

      - name: Setup vscode types
        run: npm install --save-dev @types/vscode@1.95.0

      - name: Package VSIX
        run: vsce package --allow-missing-repository

      - name: Generate artifacts
        uses: actions/upload-artifact@v4
        with:
          name: andylang-vscode
          path: "*.vsix"
